name: owe_me
description: A simple Flutter app to track personal debts, credits, and payments.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  mocktail: ^1.0.4
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true
